# Generated by Django 5.0.14 on 2025-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usagereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscriberName', models.CharField(db_column='SubscriberName', max_length=255)),
                ('DetailsViewedDate', models.DateField(db_column='DetailsViewedDate')),
                ('ProductName', models.CharField(db_column='ProductName', max_length=255)),
                ('SystemUser', models.CharField(blank=True, db_column='SystemUser', max_length=255, null=True)),
                ('SearchIdentity', models.CharField(blank=True, db_column='SearchIdentity', max_length=255, null=True)),
                ('SubscriberEnquiryDate', models.DateField(blank=True, db_column='SubscriberEnquiryDate', null=True)),
                ('SearchOutput', models.TextField(blank=True, db_column='SearchOutput', null=True)),
                ('ProductInputed', models.CharField(blank=True, db_column='ProductInputed', max_length=255, null=True)),
            ],
            options={
                'db_table': 'usagereport',
                'managed': False,
            },
        ),
    ]
