# Generated by Django 5.0.14 on 2025-05-23 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('single', 'Single Report'), ('bulk', 'Bulk Report'), ('both', 'Both Single and Bulk')], help_text='Type of report generated', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the report was generated')),
                ('subscriber_name', models.CharField(blank=True, help_text='Name of the subscriber for single reports', max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, help_text='Start date of the report period', null=True)),
                ('to_date', models.DateField(blank=True, help_text='End date of the report period', null=True)),
                ('user', models.ForeignKey(help_text='User who generated the report', on_delete=django.db.models.deletion.CASCADE, related_name='report_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Generation',
                'verbose_name_plural': 'Report Generations',
                'ordering': ['-generated_at'],
            },
        ),
    ]
