# Generated by Django 5.0.14 on 2025-05-23 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0002_reportgeneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgeneration',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the report generation was completed', null=True),
        ),
        migrations.AddField(
            model_name='reportgeneration',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the report generation failed', null=True),
        ),
        migrations.AddField(
            model_name='reportgeneration',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Additional parameters used for the report', null=True),
        ),
        migrations.AddField(
            model_name='reportgeneration',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='success', help_text='Status of the report generation', max_length=15),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='from_date',
            field=models.DateField(blank=True, db_index=True, help_text='Start date of the report period', null=True),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the report was generated'),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='report_type',
            field=models.CharField(choices=[('single', 'Single Report'), ('bulk', 'Bulk Report'), ('both', 'Both Single and Bulk')], db_index=True, help_text='Type of report generated', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='subscriber_name',
            field=models.CharField(blank=True, db_index=True, help_text='Name of the subscriber for single reports', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='to_date',
            field=models.DateField(blank=True, db_index=True, help_text='End date of the report period', null=True),
        ),
        migrations.AddIndex(
            model_name='reportgeneration',
            index=models.Index(fields=['user', 'report_type'], name='bulkrep_rep_user_id_ada17c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportgeneration',
            index=models.Index(fields=['generated_at', 'status'], name='bulkrep_rep_generat_63f5ab_idx'),
        ),
    ]
