# Generated by Django 5.0.14 on 2025-05-23 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0004_remove_reportgeneration_parameters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgeneration',
            name='generator',
            field=models.CharField(blank=True, db_index=True, default='Unknown', help_text='Name of the user who generated the report', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='user',
            field=models.ForeignKey(help_text='User who generated the report', on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
