# Generated by Django 5.0.14 on 2025-06-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0005_reportgeneration_generator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(db_column='subscriber_name', max_length=255)),
                ('product_name', models.CharField(db_column='ProductName', max_length=255)),
                ('rate', models.DecimalField(db_column='rate', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'SubscriberProductRate',
                'managed': False,
            },
        ),
    ]
