# Generated by Django 3.2.25 on 2025-11-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulkrep', '0006_subscriberproductrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the subscriber.', max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='The primary contact person for the subscriber.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='The contact email for the subscriber.', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='The contact phone number for the subscriber.', max_length=20)),
                ('managed_by', models.ForeignKey(blank=True, help_text='The manager responsible for this subscriber.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['name'],
            },
        ),
    ]
