# Generated by Django 3.2.25 on 2025-11-11 10:50

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0008_reportgeneration_subscriber_new'),
    ]

    operations = []
