# Generated by Django 5.1.3 on 2025-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0010_subscriber_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportgeneration',
            name='subscriber_new',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', help_text='Subscriber status', max_length=20),
        ),
    ]
