# Generated by Django 3.2.25 on 2025-11-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0007_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgeneration',
            name='subscriber_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports_new', to='bulkrep.subscriber'),
        ),
    ]
