# Generated by Django 3.2.25 on 2025-12-29 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulkrep', '0011_remove_reportgeneration_subscriber_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(help_text='Name of the key subscriber.', max_length=255, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this subscriber was added as a key subscriber.')),
                ('added_by', models.ForeignKey(blank=True, help_text='Admin who added this key subscriber.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_key_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Subscriber',
                'verbose_name_plural': 'Key Subscribers',
                'ordering': ['subscriber_name'],
            },
        ),
    ]
