# Generated by Django 5.1.3 on 2026-01-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0012_keysubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='contact_person_2',
            field=models.CharField(blank=True, help_text='The secondary contact person for the subscriber.', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='email_2',
            field=models.EmailField(blank=True, help_text='The secondary contact email for the subscriber.', max_length=254),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='phone_number_2',
            field=models.CharField(blank=True, help_text='The secondary contact phone number for the subscriber.', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, help_text='The primary contact email for the subscriber.', max_length=254),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(blank=True, help_text='The primary contact phone number for the subscriber.', max_length=20),
        ),
    ]
